name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "$AWS_SSH_PRIVATE_KEY" | base64 -d > private_key.pem
        chmod 600 private_key.pem
      env:
        AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }} # GitHub secret holding the base64-encoded EC2 key

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -r ./path-to-your-fastapi-app ec2-user@<EC2_PUBLIC_IP>:/home/ec2-user/fastapi-app/
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    - name: SSH to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@<EC2_PUBLIC_IP> << 'EOF'
          cd /home/ec2-user/fastapi-app
          docker-compose down
          docker-compose up -d
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
