name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode EC2 SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: Deploy via SSH
        env:
          HOST: ec2-user@54.80.94.124
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem $HOST << 'EOF'
            cd fastapi-cicd || git clone https://github.com/ROAIN1/fastapi-cicd.git && cd fastapi-cicd
            git pull origin master
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker build -t fastapi-app .
            docker run -d -p 80:80 --name fastapi-app fastapi-app
          EOF
