name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "$EC2_SSH_KEY_B64" | base64 -d > private_key.pem
        chmod 600 private_key.pem
      env:
        EC2_SSH_KEY_B64: ${{ secrets.EC2_SSH_KEY_B64 }} # Base64 encoded private key from your secret

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem -r ./path-to-your-fastapi-app ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/fastapi-app/
      env:
        EC2_USER: ${{ secrets.EC2_USER }}  # EC2 username (e.g., ec2-user)
        EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 public IP or hostname

    - name: SSH to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/fastapi-app
          docker-compose down
          docker-compose up -d
        EOF
      env:
        EC2_USER: ${{ secrets.EC2_USER }}  # EC2 username (e.g., ec2-user)
        EC2_HOST: ${{ secrets.EC2_HOST }}  # EC2 public IP or hostname
